export type CaseStudy = {
  slug: string;
  client: string;
  market: string;
  category: string;
  headline: string;
  metric: string;
  metricLabel: string;
  revenue: string;
  revenueLabel: string;
  stack: string[];
  summary: string;
  outcomes: string[];
  websiteUrl?: string;
  pdfUrl?: string;
  pdfLabel?: string;
  videoUrl?: string;
  videoLabel?: string;
  logoUrl?: string;
};
